tap "homebrew/bundle"

brew "colima"
brew "docker"
brew "git"
brew "neovim"
brew "starship"
brew "tldr"
brew "stow"
brew "z"

brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "zsh-history-substring-search"
brew "zsh-completions"

cask "nikitabobko/tap/aerospace"
cask "discord"
cask "font-jetbrains-mono-nerd-font"
cask "karabiner-elements"
cask "raycast"
cask "visual-studio-code"
cask "wezterm"
cask "dbeaver-community"
cask "notunes"
cask "obsidian"

# App to use phone as webcam
# cask "iriunwebcam"