
add_newline = false

[character]
success_symbol = "[➜](bold green)"

[line_break]
disabled = false

[aws]
symbol = "  "

[c]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = "  "

[docker_context]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[haxe]
symbol = "⌘ "

[java]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[nodejs]
symbol = " "

[package]
symbol = "󰏗 "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "
